import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'

function generatePackingListHTML(order: any): string {
  const items = order.order_items ?? []
  const consignee = order.consignees
  const addr = order.consignee_addresses

  const itemRows = items.map((item: any) => `
    <tr>
      <td>${item.skus?.sku_code ?? ''}</td>
      <td>${item.skus?.description ?? ''}</td>
      <td style="text-align:right">${item.quantity}</td>
      <td style="text-align:right">${item.carton_count ?? '—'}</td>
      <td style="text-align:right">${item.units_per_carton ?? '—'}</td>
      <td style="text-align:right">${item.weight_kg ?? '—'}</td>
    </tr>
  `).join('')

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: Arial, sans-serif; font-size: 11px; color: #1a1a1a; margin: 40px; }
  h1 { font-size: 20px; margin: 0 0 4px; }
  .header { display: flex; justify-content: space-between; margin-bottom: 24px; border-bottom: 2px solid #1d4ed8; padding-bottom: 16px; }
  .company { font-size: 18px; font-weight: bold; color: #1d4ed8; }
  .doc-title { text-align: right; }
  .doc-title h1 { color: #1d4ed8; }
  .doc-title p { color: #666; margin: 2px 0; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 24px; }
  .section { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 4px; padding: 12px; }
  .section h3 { margin: 0 0 8px; font-size: 10px; text-transform: uppercase; color: #64748b; letter-spacing: 0.05em; }
  .section p { margin: 2px 0; font-size: 11px; }
  table { width: 100%; border-collapse: collapse; margin-top: 8px; }
  th { background: #1d4ed8; color: white; padding: 8px 10px; text-align: left; font-size: 10px; text-transform: uppercase; }
  th:last-child, td:last-child { text-align: right; }
  td { padding: 7px 10px; border-bottom: 1px solid #f1f5f9; font-size: 11px; }
  tr:nth-child(even) td { background: #f8fafc; }
  .totals { text-align: right; margin-top: 12px; font-size: 12px; }
  .totals strong { font-size: 13px; }
  .footer { margin-top: 32px; border-top: 1px solid #e2e8f0; padding-top: 12px; font-size: 10px; color: #94a3b8; }
</style>
</head>
<body>
<div class="header">
  <div class="company">CTS Portal</div>
  <div class="doc-title">
    <h1>Packing List</h1>
    <p><strong>Order:</strong> ${order.order_number}</p>
    <p><strong>Date:</strong> ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
    ${order.ship_by_date ? `<p><strong>Ship by:</strong> ${new Date(order.ship_by_date).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>` : ''}
  </div>
</div>

<div class="grid">
  <div class="section">
    <h3>Shipper</h3>
    <p><strong>${order.customers?.name ?? 'Customer'}</strong></p>
    <p>${order.customers?.billing_email ?? ''}</p>
  </div>
  <div class="section">
    <h3>Consignee / Ship To</h3>
    ${consignee ? `<p><strong>${consignee.company_name}</strong></p>` : ''}
    ${consignee?.contact_name ? `<p>${consignee.contact_name}</p>` : ''}
    ${addr ? `
      <p>${addr.address_line1}</p>
      ${addr.address_line2 ? `<p>${addr.address_line2}</p>` : ''}
      <p>${addr.city}, ${addr.state} ${addr.postal_code}</p>
    ` : ''}
    ${consignee?.contact_phone ? `<p>${consignee.contact_phone}</p>` : ''}
  </div>
</div>

<table>
  <thead>
    <tr>
      <th>SKU</th>
      <th>Description</th>
      <th style="text-align:right">Qty</th>
      <th style="text-align:right">Cartons</th>
      <th style="text-align:right">Units/Ctn</th>
      <th style="text-align:right">Weight (lb)</th>
    </tr>
  </thead>
  <tbody>${itemRows}</tbody>
</table>

<div class="totals">
  <p>Total pallets: <strong>${order.pallet_count}</strong></p>
  <p>Total lines: <strong>${items.length}</strong></p>
</div>

${order.delivery_instructions ? `<div class="section" style="margin-top:16px"><h3>Delivery Instructions</h3><p>${order.delivery_instructions}</p></div>` : ''}
${order.notes ? `<div class="section" style="margin-top:8px"><h3>Notes</h3><p>${order.notes}</p></div>` : ''}

<div class="footer">
  <p>Generated by CTS Portal · ${new Date().toISOString()}</p>
</div>
</body>
</html>`
}

function generateBOLHTML(order: any): string {
  const consignee = order.consignees
  const addr = order.consignee_addresses
  const items = order.order_items ?? []
  const totalQty = items.reduce((sum: number, i: any) => sum + (i.quantity || 0), 0)
  const totalCartons = items.reduce((sum: number, i: any) => sum + (i.carton_count || 0), 0)

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: Arial, sans-serif; font-size: 11px; color: #1a1a1a; margin: 40px; }
  .header { display: flex; justify-content: space-between; margin-bottom: 24px; border-bottom: 2px solid #1d4ed8; padding-bottom: 16px; }
  .company { font-size: 18px; font-weight: bold; color: #1d4ed8; }
  .doc-title { text-align: right; }
  .doc-title h1 { font-size: 20px; color: #1d4ed8; margin: 0 0 4px; }
  .doc-title p { color: #666; margin: 2px 0; }
  .grid2 { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 16px; }
  .grid3 { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 16px; margin-bottom: 16px; }
  .box { border: 1px solid #e2e8f0; border-radius: 4px; padding: 12px; }
  .box h3 { margin: 0 0 8px; font-size: 10px; text-transform: uppercase; color: #64748b; letter-spacing: 0.05em; }
  .box p { margin: 2px 0; }
  table { width: 100%; border-collapse: collapse; }
  th { background: #1d4ed8; color: white; padding: 8px 10px; text-align: left; font-size: 10px; }
  td { padding: 7px 10px; border-bottom: 1px solid #f1f5f9; }
  .sig-row { display: grid; grid-template-columns: 1fr 1fr; gap: 32px; margin-top: 32px; }
  .sig-box { border-top: 1px solid #1a1a1a; padding-top: 8px; font-size: 10px; color: #64748b; }
  .footer { margin-top: 24px; border-top: 1px solid #e2e8f0; padding-top: 12px; font-size: 10px; color: #94a3b8; }
</style>
</head>
<body>
<div class="header">
  <div class="company">CTS Portal<br><span style="font-size:11px;font-weight:normal;color:#64748b">Bill of Lading</span></div>
  <div class="doc-title">
    <h1>Bill of Lading</h1>
    <p><strong>BOL #:</strong> ${order.order_number}</p>
    <p><strong>Date:</strong> ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
    ${order.carrier ? `<p><strong>Carrier:</strong> ${order.carrier}</p>` : ''}
    ${order.tracking_number ? `<p><strong>PRO/Tracking:</strong> ${order.tracking_number}</p>` : ''}
  </div>
</div>

<div class="grid2">
  <div class="box">
    <h3>Shipper</h3>
    <p><strong>${order.customers?.name ?? ''}</strong></p>
    <p>${order.customers?.billing_email ?? ''}</p>
  </div>
  <div class="box">
    <h3>Consignee</h3>
    ${consignee ? `<p><strong>${consignee.company_name}</strong></p>` : ''}
    ${consignee?.contact_name ? `<p>${consignee.contact_name}</p>` : ''}
    ${consignee?.contact_phone ? `<p>${consignee.contact_phone}</p>` : ''}
    ${addr ? `
      <p>${addr.address_line1}${addr.address_line2 ? ', ' + addr.address_line2 : ''}</p>
      <p>${addr.city}, ${addr.state} ${addr.postal_code}</p>
    ` : ''}
  </div>
</div>

<div class="grid3">
  <div class="box">
    <h3>Ship Date</h3>
    <p>${order.ship_by_date ? new Date(order.ship_by_date).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) : '____________'}</p>
  </div>
  <div class="box">
    <h3>Pallets</h3>
    <p><strong>${order.pallet_count}</strong></p>
  </div>
  <div class="box">
    <h3>Total Cartons</h3>
    <p><strong>${totalCartons || '—'}</strong></p>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th>SKU</th>
      <th>Description</th>
      <th>Qty</th>
      <th>Cartons</th>
      <th>Weight (lb)</th>
    </tr>
  </thead>
  <tbody>
    ${items.map((item: any) => `
      <tr>
        <td>${item.skus?.sku_code ?? ''}</td>
        <td>${item.skus?.description ?? ''}</td>
        <td>${item.quantity}</td>
        <td>${item.carton_count ?? '—'}</td>
        <td>${item.weight_kg ?? '—'}</td>
      </tr>
    `).join('')}
  </tbody>
</table>

${order.delivery_instructions ? `<div class="box" style="margin-top:16px"><h3>Special Instructions</h3><p>${order.delivery_instructions}</p></div>` : ''}

<div class="sig-row">
  <div class="sig-box">Shipper Signature &amp; Date</div>
  <div class="sig-box">Carrier Signature &amp; Date</div>
</div>

<div class="footer">
  <p>Generated by CTS Portal · ${new Date().toISOString()}</p>
  <p>This document serves as a receipt of the goods described above.</p>
</div>
</body>
</html>`
}

// ── Shared fetch helper ───────────────────────────────────────────────────────

async function fetchOrder(supabase: any, order_id: string) {
  const { data } = await supabase
    .from('orders')
    .select('*, customers(name, billing_email), consignees(company_name, contact_name, contact_phone), consignee_addresses:consignee_address_id(*), order_items(*, skus(sku_code, description, unit))')
    .eq('id', order_id)
    .single()
  return data
}

// ── GET — serve HTML directly (no popup-blocker issues, no signed-URL expiry)
// Usage: /api/pdf?order_id=xxx&type=packing_list|bill_of_lading
export async function GET(req: NextRequest) {
  try {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return new Response('Unauthorized', { status: 401 })

    const { searchParams } = new URL(req.url)
    const order_id = searchParams.get('order_id') ?? ''
    const type = searchParams.get('type') ?? ''
    if (!order_id || !['packing_list', 'bill_of_lading'].includes(type)) {
      return new Response('Invalid request', { status: 400 })
    }

    const order = await fetchOrder(supabase, order_id)
    if (!order) return new Response('Order not found', { status: 404 })

    const html = type === 'packing_list' ? generatePackingListHTML(order) : generateBOLHTML(order)

    // Save to storage + documents table as a best-effort side-effect
    const filename = `${type === 'packing_list' ? 'PackingList' : 'BOL'}-${order.order_number}.html`
    const storagePath = `${order.customer_id}/${order_id}/${filename}`
    const htmlBuf = Buffer.from(html)
    ;(async () => {
      const { error: uploadErr } = await supabase.storage
        .from('documents')
        .upload(storagePath, htmlBuf, { contentType: 'text/html', upsert: true })
      if (!uploadErr) {
        await supabase.from('documents').insert({
          order_id, customer_id: order.customer_id, document_type: type,
          filename, storage_path: storagePath,
          file_size_bytes: htmlBuf.length,
          uploaded_by: user.id, is_generated: true,
        }).then(() => {}) // best-effort, ignore duplicate errors
      }
    })()

    return new Response(html, {
      headers: { 'Content-Type': 'text/html; charset=utf-8' },
    })
  } catch (e: any) {
    return new Response(e.message, { status: 500 })
  }
}

export async function POST(req: NextRequest) {
  try {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const { order_id, type } = await req.json()
    if (!order_id || !['packing_list', 'bill_of_lading'].includes(type)) {
      return NextResponse.json({ error: 'Invalid request' }, { status: 400 })
    }

    const order = await fetchOrder(supabase, order_id)
    if (!order) return NextResponse.json({ error: 'Order not found' }, { status: 404 })

    const html = type === 'packing_list' ? generatePackingListHTML(order) : generateBOLHTML(order)
    const filename = `${type === 'packing_list' ? 'PackingList' : 'BOL'}-${order.order_number}.html`
    const storagePath = `${order.customer_id}/${order_id}/${filename}`

    // Store HTML as file in Supabase storage
    const { error: uploadError } = await supabase.storage
      .from('documents')
      .upload(storagePath, Buffer.from(html), { contentType: 'text/html', upsert: true })

    if (uploadError) return NextResponse.json({ error: uploadError.message }, { status: 500 })

    // Record in documents table
    const { data: doc, error: docError } = await supabase.from('documents').insert({
      order_id,
      customer_id: order.customer_id,
      document_type: type,
      filename,
      storage_path: storagePath,
      file_size_bytes: Buffer.from(html).length,
      uploaded_by: user.id,
      is_generated: true,
    }).select().single()

    if (docError) return NextResponse.json({ error: docError.message }, { status: 500 })

    // Get signed URL
    const { data: signedData } = await supabase.storage
      .from('documents')
      .createSignedUrl(storagePath, 60 * 60 * 24)

    return NextResponse.json({ success: true, document: doc, url: signedData?.signedUrl })
  } catch (e: any) {
    return NextResponse.json({ error: e.message }, { status: 500 })
  }
}
